### ISSUE TITLE
I can't install this extension

### ISSUE THREAD

**Issue by missjewel** [webmaxx/yii2-materialize#2]
my console gets stuck when I try to install it

![consola](https://cloud.githubusercontent.com/assets/11300452/6849211/ffa9fd28-d3a3-11e4-8b6a-944f9a6555c9.PNG)

**Comment by webmaxx** [comment]
In "require" section your "composer.json" file:

```
"webmaxx/yii2-materialize": "dev-master"
```

In console use:

```
# composer clear-cache
$ composer update
```

and wait (~5 minutes)
Bower is stupid :)

**Comment by missjewel** [comment]
I give me a error again. 
![error](https://cloud.githubusercontent.com/assets/11300452/6857063/55b23f28-d3d6-11e4-8453-e541ea9ffa0d.PNG)

**Comment by webmaxx** [comment]
Using `# composer global require "fxp/composer-asset-plugin:1.0.0"` ?

**Comment by webmaxx** [comment]
And please show your composer.json file.

**Comment by webmaxx** [comment]
Ok. Should work now.

**Comment by webmaxx** [comment]
Ok. Should work now.
